variable "subscription_id" {
  type        = string
  description = "The Azure Subscription where you want to deploy unipipe"
}
variable "resource_group_name" {
  type        = string
  default     = "rg-unipipe-demo"
  description = "Name of the resource group to deploy unipipe"
}
variable "location" {
  type        = string
  default     = "West Europe"
  description = "The Azure region to use for deployment"
}
variable "location_tag" {
  type        = string
  default     = "westeurope"
  description = "location tag, needs to match the location variable"
}
variable "dns_name_label" {
  type        = string
  default     = "unipipe-demo"
  description = "controls the hostname for the FQDN auto-generated by Azure ACI"
}
variable "unipipe_version" {
  type        = string
  default     = "latest"
  description = "unipipe version, see https://github.com/meshcloud/unipipe-service-broker/releases"
}
variable "unipipe_basic_auth_username" {
  type        = string
  default     = "user"
  description = "OSB API basic auth username. Password will be generated by terraform."
}
variable "unipipe_git_remote" {
  type        = string
  description = "git repo URL, use a deploy key (GitHub) or similar to setup an automation user SSH key for unipipe"
}
variable "unipipe_git_branch" {
  type        = string
  default     = "main"
  description = "git branch name"
}
